const AUTH = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SET_USER: 'SET_USER',
    LOGOUT: 'USERS_LOGOUT',
    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    RESET_MESSAGES: 'AUTH_RESET_MESSAGES',
    START_ISLOADING: 'AUTH_START_ISLOADING',
    STOP_ISLOADING: 'AUTH_STOP_ISLOADING'
}

const ALBUMS = {
    LOAD: 'ALBUMS_LOAD',
    LOAD_SUCCESS: 'ALBUMS_LOAD_SUCCESS',
    LOAD_FAIL: 'ALBUMS_LOAD_FAIL',
    ADD_NEW_ALBUM: 'ADD_NEW_ALBUM',
    ADD_NEW_ALBUM_SUCCESS: 'ADD_NEW_ALBUM_SUCCESS',
    ADD_NEW_ALBUM_FAILED: 'ADD_NEW_ALBUM_FAILED',
    RESET_MESSAGES: 'ALBUMS_RESET_MESSAGES',
    START_ISLOADING: 'ALBUMS_START_ISLOADING',
    STOP_ISLOADING: 'ALBUMS_STOP_ISLOADING',
    DELETE_ALBUM: 'DELETE_ALBUM',
    DELETE_ALBUM_SUCCESS: 'DELETE_ALBUM_SUCCESS',
    DELETE_ALBUM_FAILED: 'DELETE_ALBUM_FAILED',
    EDIT_ALBUM: 'EDIT_ALBUM',
    EDIT_ALBUM_SUCCESS: 'EDIT_ALBUM_SUCCESS',
    EDIT_ALBUM_FAILED: 'EDIT_ALBUM_FAILED'
};

const PHOTOS = {
    LOAD: 'PHOTOS_LOAD',
    LOAD_SUCCESS: 'PHOTOS_LOAD_SUCCESS',
    LOAD_FAIL: 'PHOTOS_LOAD_FAIL',
    UPLOAD_PHOTOS: 'PHOTOS_UPLOAD_PHOTOS',
    START_ISLOADING: 'PHOTOS_START_ISLOADING',
    STOP_ISLOADING: 'PHOTOS_STOP_ISLOADING',
    CLEAR_PHOTOS: 'CLEAR_PHOTOS',
    RESET_MESSAGES: 'PHOTOS_RESET_MESSAGES',
    ADD_PHOTO_SUCCESS: 'ADD_PHOTO_SUCCESS',
    ADD_PHOTO_FAILED: 'ADD_PHOTO_FAILED',
    DELETE_PHOTO: 'DELETE_PHOTO',
    DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
    DELETE_PHOTO_FAILED: 'DELETE_PHOTO_FAILED',
    EDIT_PHOTO: 'EDIT_PHOTO',
    EDIT_PHOTO_SUCCESS: 'EDIT_PHOTO_SUCCESS',
    EDIT_PHOTO_FAILED: 'EDIT_PHOTO_FAILED'
};

export { AUTH, ALBUMS, PHOTOS };
